config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('medic.urls', namespace='medic')),
    path('users/', include('users.urls', namespace='users')),
    path('doctors/', include('doctors.urls', namespace='doctors')),
]

doctors/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import (
    ClassificationListView,
    ClassificationCreateView,
    ClassificationDetailView,
    ClassificationUpdateView,
    ClassificationDeleteView,
    DoctorListView,
    DoctorCreateView,
    DoctorDetailView,
    DoctorUpdateView,
    DoctorDeleteView,
)

app_name = 'doctors'


urlpatterns = [
    # Classification
    path('classifications/', ClassificationListView.as_view(), name='classification_list'),
    path('classifications/create/', ClassificationCreateView.as_view(), name='classification_create'),
    path('classifications/<int:pk>/', ClassificationDetailView.as_view(), name='classification_detail'),
    path('classifications/update/<int:pk>/', ClassificationUpdateView.as_view(), name='classification_update'),
    path('classifications/delete/<int:pk>/', ClassificationDeleteView.as_view(), name='classification_delete'),

    # Doctor
    path('', DoctorListView.as_view(), name='doctor_list'),
    path('create/', DoctorCreateView.as_view(), name='doctor_create'),
    path('<int:pk>/', DoctorDetailView.as_view(), name='doctor_detail'),
    path('update/<int:pk>/', DoctorUpdateView.as_view(), name='doctor_update'),
    path('delete/<int:pk>/', DoctorDeleteView.as_view(), name='doctor_delete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

medic/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import (
    main_view,
    DiagnosticListView, DiagnosticCreateView, DiagnosticDetailView,
    DiagnosticUpdateView, DiagnosticDeleteView,
    RecordListView, RecordCreateView, RecordDetailView,
    RecordUpdateView, RecordDeleteView,
    ResultListView, ResultCreateView, ResultDetailView,
    ResultUpdateView, ResultDeleteView,
)

app_name = 'medic'

urlpatterns = [
    # Main view
    path('', main_view, name='main'),

    # Diagnostic URLs
    path('diagnostics/', DiagnosticListView.as_view(), name='diagnostic_list'),
    path('diagnostics/create/', DiagnosticCreateView.as_view(), name='diagnostic_create'),
    path('diagnostics/<int:pk>/', DiagnosticDetailView.as_view(), name='diagnostic_detail'),
    path('diagnostics/<int:pk>/update/', DiagnosticUpdateView.as_view(), name='diagnostic_update'),
    path('diagnostics/<int:pk>/delete/', DiagnosticDeleteView.as_view(), name='diagnostic_delete'),

    # Record URLs
    path('records/', RecordListView.as_view(), name='record_list'),
    path('records/create/', RecordCreateView.as_view(), name='record_create'),
    path('records/<int:pk>/', RecordDetailView.as_view(), name='record_detail'),
    path('records/<int:pk>/update/', RecordUpdateView.as_view(), name='record_update'),
    path('records/<int:pk>/delete/', RecordDeleteView.as_view(), name='record_delete'),

    # Result URLs
    path('results/', ResultListView.as_view(), name='result_list'),
    path('results/create/', ResultCreateView.as_view(), name='result_create'),
    path('results/<int:pk>/', ResultDetailView.as_view(), name='result_detail'),
    path('results/<int:pk>/update/', ResultUpdateView.as_view(), name='result_update'),
    path('results/<int:pk>/delete/', ResultDeleteView.as_view(), name='result_delete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.views import RegisterView, ProfileView, activate, ProfileUpdateView, ReviewListView, ReviewCreateView

app_name = 'users'

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/edit/', ProfileUpdateView.as_view(), name='profile_edit'),
    path('activate/<uidb64>/<token>/', activate, name='verify_email'),

    path('reviews/', ReviewListView.as_view(), name='review_list'),
    path('reviews/create/', ReviewCreateView.as_view(), name='review_create'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

medic/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone

from doctors.models import Doctor
from users.models import NULLABLE
from datetime import time


# Диагностики
class Diagnostic(models.Model):
    title = models.CharField(max_length=100, verbose_name='название')
    description = models.TextField(verbose_name='описание')
    price = models.IntegerField(verbose_name='цена')
    image = models.ImageField(upload_to='media/', **NULLABLE, verbose_name='фото')

    def __str__(self):
        return f"{self.title}"

    class Meta:
        verbose_name = 'диагностика'
        verbose_name_plural = 'диагностики'


# Запись на диагонстику
class Record(models.Model):
    patient = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='пациент')
    diagnostic = models.ForeignKey(Diagnostic, on_delete=models.CASCADE, verbose_name='диагностика')
    date = models.DateField(verbose_name='дата записи')
    time = models.TimeField(default=time(0, 0), verbose_name='время записи')
    doctors = models.ForeignKey(Doctor, on_delete=models.CASCADE, verbose_name='врачи')
    reason = models.TextField(**NULLABLE, verbose_name='причина записи')
    wishes = models.TextField(**NULLABLE, verbose_name='пожелания')

    def __str__(self):
        return f"{self.patient.first_name} {self.patient.last_name} ({self.patient}) записался/записалась на {self.diagnostic} к врачу {self.doctors}, дата: {self.date}"

    class Meta:
        verbose_name = 'запись на диагонстику'
        verbose_name_plural = 'записи на диагонстику'


# Результаты
class Result(models.Model):
    title = models.CharField(max_length=200, verbose_name='название результатов')
    patient = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='пациент')
    date = models.DateField(default=timezone.now, verbose_name='дата результатов')
    result = models.TextField(verbose_name='результат')
    description = models.TextField(**NULLABLE, verbose_name='описание')
    medication = models.TextField(verbose_name='лечение')

    def __str__(self):
        return f"{self.title} {self.result} {self.medication}, пациенту: {self.patient}"

    class Meta:
        verbose_name = 'результат'
        verbose_name_plural = 'результаты'

medic/forms.py
from django import forms
from .models import Diagnostic, Record, Result


class DiagnosticForm(forms.ModelForm):
    class Meta:
        model = Diagnostic
        fields = ['title', 'description', 'price', 'image']
        labels = {
            'title': 'Название диагностики',
            'description': 'Описание',
            'price': 'Цена',
            'image': 'Фото',
        }


class RecordForm(forms.ModelForm):
    class Meta:
        model = Record
        fields = ['patient', 'diagnostic', 'date', 'time', 'doctors', 'reason', 'wishes']
        labels = {
            'patient': 'Пациент',
            'diagnostic': 'Диагностика',
            'date': 'Дата записи',
            'doctors': 'Врач',
            'wishes': 'Пожелания',
        }


class ResultForm(forms.ModelForm):
    class Meta:
        model = Result
        fields = ['title', 'patient', 'result', 'description', 'medication']
        labels = {
            'title': 'Название результатов',
            'patient': 'Пациент',
            'result': 'Результат',
            'description': 'Описание',
            'medication': 'Лечение',
        }

medic/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from django.urls import reverse_lazy

from doctors.models import Doctor
from .models import Diagnostic, Record, Result
from .forms import DiagnosticForm, RecordForm, ResultForm


# Main
def main_view(request):
    doctors = Doctor.objects.all()[:3]
    diagnostics = Diagnostic.objects.filter(id__in=[4, 5, 6])
    context = {
        'doctors': doctors,
        'diagnostics': diagnostics,
    }
    return render(request, 'medic/main.html', context)


# DIAGNOSTIC
class DiagnosticListView(ListView):
    model = Diagnostic
    template_name = 'medic/diagnostic_list.html'
    context_object_name = 'diagnostics'


class DiagnosticCreateView(CreateView):
    model = Diagnostic
    form_class = DiagnosticForm
    template_name = 'medic/diagnostic_form.html'
    success_url = reverse_lazy('medic:diagnostic_list')


class DiagnosticDetailView(DetailView):
    model = Diagnostic
    template_name = 'medic/diagnostic_detail.html'
    context_object_name = 'diagnostic'


class DiagnosticUpdateView(UpdateView):
    model = Diagnostic
    form_class = DiagnosticForm
    template_name = 'medic/diagnostic_form.html'
    success_url = reverse_lazy('medic:diagnostic_list')


class DiagnosticDeleteView(DeleteView):
    model = Diagnostic
    template_name = 'medic/diagnostic_confirm_delete.html'
    success_url = reverse_lazy('diagnostic_list')


# RECORD
class RecordListView(ListView):
    model = Record
    template_name = 'medic/record_list.html'
    context_object_name = 'records'


class RecordCreateView(CreateView):
    model = Record
    form_class = RecordForm
    template_name = 'medic/record_form.html'
    success_url = reverse_lazy('medic:record_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Добавляем врачей и диагностику в контекст
        context['doctors'] = Doctor.objects.all()
        context['diagnostics'] = Diagnostic.objects.all()
        return context

    def form_valid(self, form):
        # Устанавливаем текущего пользователя как пациента
        form.instance.patient = self.request.user
        return super().form_valid(form)


class RecordDetailView(DetailView):
    model = Record
    template_name = 'medic/record_detail.html'
    context_object_name = 'record'


class RecordUpdateView(UpdateView):
    model = Record
    form_class = RecordForm
    template_name = 'medic/record_form.html'
    success_url = reverse_lazy('record_list')


class RecordDeleteView(DeleteView):
    model = Record
    template_name = 'record_confirm_delete.html'
    success_url = reverse_lazy('record_list')


# RESULT
class ResultListView(ListView):
    model = Result
    template_name = 'medic/result_list.html'
    context_object_name = 'results'


class ResultCreateView(CreateView):
    model = Result
    form_class = ResultForm
    template_name = 'medic/result_form.html'
    success_url = reverse_lazy('result_list')


class ResultDetailView(DetailView):
    model = Result
    template_name = 'medic/result_detail.html'
    context_object_name = 'result'


class ResultUpdateView(UpdateView):
    model = Result
    form_class = ResultForm
    template_name = 'medic/result_form.html'
    success_url = reverse_lazy('result_list')


class ResultDeleteView(DeleteView):
    model = Result
    template_name = 'result_confirm_delete.html'
    success_url = reverse_lazy('result_list')

medic/templates/medic/includes/base.html
{% load static %}
<!doctype html>

  <script type="text/javascript" src="{% static 'js/main.js' %}" charset="UTF-8"></script><link rel="stylesheet" crossorigin="anonymous" href="{% static 'css/main.css' %}"/><script src="{% static 'js/color-models.js' %}"></script>

    <title>Medic RU</title>

    <link rel="stylesheet" href="{% static 'css/docsearch.css' %}">
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">



<header data-bs-theme="dark">
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'medic:main' %}">MEDIC.RU</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'medic:main' %}">На главную</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'medic:diagnostic_list' %}">Наши услуги</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'doctors:doctor_list' %}">Врачи</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'doctors:classification_list' %}">Классификации</a>
          </li>
          <li class="nav-item">
            {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'users:profile' %}">Профиль</a>
            {% else %}
            <a class="nav-link" href="{% url 'users:login' %}">Войти</a>
            {% endif %}
          </li>
        </ul>
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-primary" type="submit" style="color: #00b7c2; border-color: #00b7c2;">
           Поиск
          </button>
       </form>
      </div>
    </div>
  </nav>
</header>


  {% block content %}
  {% endblock %}


  <!-- FOOTER -->
  <footer class="container">
    <p class="float-end"><a href="#" class="scroll-up"><i class="fas fa-arrow-up" style="font-size: 32px; transition: transform 0.3s;"></i></a></p>
    <p>&copy; 2024 MEDIC, Inc. &middot; <a href="#">Контакты</a> &middot; <a href="#">Условия</a></p>
</footer>

<style>
    .scroll-up {
        display: inline-block;
        margin-left: 5px;
        margin-top: 15px;
        color: #007bff;
        transition: transform 0.3s, color 0.3s;
    }

    .scroll-up:hover {
        transform: scale(1.3);
        color: #0056b3;
    }

</style>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

    </body>
</html>